# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-17 02:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import system.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u5408\u540c\u540d\u79f0')),
                ('company_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u4f9b\u5e94\u5546\u540d\u79f0')),
                ('responsible', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u4f9b\u5e94\u5546\u8d1f\u8d23\u4eba')),
                ('phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='\u8d1f\u8d23\u4eba\u7535\u8bdd')),
                ('start_date', models.DateField(verbose_name='\u5408\u540c\u5f00\u59cb\u65e5\u671f')),
                ('end_date', models.DateField(verbose_name='\u5408\u540c\u7ed3\u675f\u65e5\u671f')),
                ('days', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u5230\u671f\u5929\u6570')),
                ('remark', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u5907\u6ce8')),
                ('upload_file', models.FileField(blank=True, null=True, storage=system.storage.FileStorage(), upload_to='upload/%Y/%m/%d', verbose_name='\u6587\u4ef6')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('change_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u5408\u540c\u540d\u79f0',
                'verbose_name_plural': '\u5408\u540c\u540d\u79f0',
            },
        ),
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(max_length=10, verbose_name='\u5408\u540c\u7c7b\u578b\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u5408\u540c\u7c7b\u578b',
                'verbose_name_plural': '\u5408\u540c\u7c7b\u578b',
            },
        ),
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workplace_name', models.CharField(max_length=10, verbose_name='\u804c\u573a\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u804c\u573a\u540d\u79f0',
                'verbose_name_plural': '\u804c\u573a\u540d\u79f0',
            },
        ),
        migrations.AddField(
            model_name='contractadmin',
            name='contract_admin_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.ContractType'),
        ),
        migrations.AddField(
            model_name='contractadmin',
            name='contract_admin_workplace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.Workplace'),
        ),
    ]
