# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-20 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='\u7528\u6237\u540d')),
                ('alias', models.CharField(max_length=20, verbose_name='\u4e2d\u6587\u540d')),
                ('password', models.CharField(max_length=30, verbose_name='\u5bc6\u7801')),
                ('phone', models.CharField(max_length=13, verbose_name='\u624b\u673a\u53f7\u7801')),
                ('email', models.EmailField(max_length=254, verbose_name='\u90ae\u7bb1')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u540d',
                'verbose_name_plural': '\u7528\u6237\u540d',
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(max_length=10, verbose_name='\u7528\u6237\u7c7b\u578b\u540d')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u7c7b\u578b\u540d',
                'verbose_name_plural': '\u7528\u6237\u7c7b\u578b\u540d',
            },
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_info_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.UserType'),
        ),
    ]
